name: Build LaTeX document
on: [push]
jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: 3.9
      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install numpy Pillow
      - name: Generate Sacks spiral image
        run: |
          python .\sacks_spiral.py
      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v2
        with:
          root_file: |
              main.tex
      - name: Upload document
        uses: actions/upload-artifact@v2
        with:
          name: notes
          path: "main.pdf"
          if-no-files-found: error
